name: Static Analysis
on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
        - run: echo "🎉 The job was automatically triggered by ${{ github.event_name }}."
        - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Install poetry
          run: pipx install poetry
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            cache: 'poetry'
        - name: Install package
          shell: bash
          working-directory: ./wetter
          run: poetry install --no-interaction --no-ansi -vv
        - name: Activate environment
          working-directory: ./wetter
          shell: bash
          run: |
            if [ "$RUNNER_OS" == "Windows" ]; then
                source $(poetry env info --path)\\Scripts\\activate;
            else
                source $(poetry env info --path)/bin/activate;
            fi
            python -c "import wetter"
        - name: Run Black8 formatting
          shell: bash
          working-directory: ./wetter
          run: poetry run black --color --diff --check .
        - name: Run flake8 linting
          shell: bash
          working-directory: ./wetter
          run: poetry run flake8 . --count --show-source --statistics
